Sub PopulateFacultyIndex(facultyIndex As Variant)
    ReDim facultyIndex(31, 2) As Variant
    'index keys
        facultyIndex(0, 0) = 1
        facultyIndex(1, 0) = 2
        facultyIndex(2, 0) = 3
        facultyIndex(3, 0) = 4
        facultyIndex(4, 0) = 5
        facultyIndex(5, 0) = 6
        facultyIndex(6, 0) = 7
        facultyIndex(7, 0) = 8
        facultyIndex(8, 0) = 9
        facultyIndex(9, 0) = 10
        facultyIndex(10, 0) = 11
        facultyIndex(11, 0) = 12
        facultyIndex(12, 0) = 13
        facultyIndex(13, 0) = 14
        facultyIndex(14, 0) = 15
        facultyIndex(15, 0) = 16
        facultyIndex(16, 0) = 17
        facultyIndex(17, 0) = 18
        facultyIndex(18, 0) = 19
        facultyIndex(19, 0) = 20
        facultyIndex(20, 0) = 21
        facultyIndex(21, 0) = 22
        facultyIndex(22, 0) = 23
        facultyIndex(23, 0) = 24
        facultyIndex(24, 0) = 25
        facultyIndex(25, 0) = 26
        facultyIndex(26, 0) = 27
        facultyIndex(27, 0) = 28
        facultyIndex(28, 0) = 29
        facultyIndex(29, 0) = 30
        facultyIndex(30, 0) = 31
        facultyIndex(31, 0) = 32
    'Faculty Values
        facultyIndex(0, 1) = "Akram Ahmed"
        facultyIndex(1, 1) = "Tamara Babaian"
        facultyIndex(2, 1) = "Jay Cooprider"
        facultyIndex(3, 1) = "Mark Frydenberg"
        facultyIndex(4, 1) = "Monica Garfield"
        facultyIndex(5, 1) = "Vatche Ishakian"
        facultyIndex(6, 1) = "Wendy Lucas"
        facultyIndex(7, 1) = "Elizabeth McCarron"
        facultyIndex(8, 1) = "Bill Vanderclock"
        facultyIndex(9, 1) = "James Pape"
        facultyIndex(10, 1) = "Bill Schiano"
        facultyIndex(11, 1) = "Heikki Topi"
        facultyIndex(12, 1) = "Bill Vanderclock"
        facultyIndex(13, 1) = "Les Waguespack"
        facultyIndex(14, 1) = "Jennifer Xu"
        facultyIndex(15, 1) = "David Yates"
        facultyIndex(16, 1) = "Donald Aucoin"
        facultyIndex(17, 1) = "Michael Banks"
        facultyIndex(18, 1) = "Anstasia Biggs"
        facultyIndex(19, 1) = "Mimoza Dimodugno"
        facultyIndex(20, 1) = "Joed Graf"
        facultyIndex(21, 1) = "Andrea Jones"
        facultyIndex(22, 1) = "Matthew Macarty"
        facultyIndex(23, 1) = "Joseph Nezuh"
        facultyIndex(24, 1) = "Anne Pugliese"
        facultyIndex(25, 1) = "Trish Rice"
        facultyIndex(26, 1) = "David Rude"
        facultyIndex(27, 1) = "Gaurav Shah"
        facultyIndex(28, 1) = "Daniel Sheehan"
        facultyIndex(29, 1) = "Robert Stubbs"
        facultyIndex(30, 1) = "Stephen Tracy"
        facultyIndex(31, 1) = "Charles Wright"
End Sub
